// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.3
// source: proto/template.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CriticalService_RequestCritical_FullMethodName = "/proto.CriticalService/RequestCritical"
)

// CriticalServiceClient is the client API for CriticalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CriticalServiceClient interface {
	RequestCritical(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
}

type criticalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCriticalServiceClient(cc grpc.ClientConnInterface) CriticalServiceClient {
	return &criticalServiceClient{cc}
}

func (c *criticalServiceClient) RequestCritical(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, CriticalService_RequestCritical_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CriticalServiceServer is the server API for CriticalService service.
// All implementations must embed UnimplementedCriticalServiceServer
// for forward compatibility
type CriticalServiceServer interface {
	RequestCritical(context.Context, *Request) (*Reply, error)
	mustEmbedUnimplementedCriticalServiceServer()
}

// UnimplementedCriticalServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCriticalServiceServer struct {
}

func (UnimplementedCriticalServiceServer) RequestCritical(context.Context, *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestCritical not implemented")
}
func (UnimplementedCriticalServiceServer) mustEmbedUnimplementedCriticalServiceServer() {}

// UnsafeCriticalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CriticalServiceServer will
// result in compilation errors.
type UnsafeCriticalServiceServer interface {
	mustEmbedUnimplementedCriticalServiceServer()
}

func RegisterCriticalServiceServer(s grpc.ServiceRegistrar, srv CriticalServiceServer) {
	s.RegisterService(&CriticalService_ServiceDesc, srv)
}

func _CriticalService_RequestCritical_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CriticalServiceServer).RequestCritical(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CriticalService_RequestCritical_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CriticalServiceServer).RequestCritical(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// CriticalService_ServiceDesc is the grpc.ServiceDesc for CriticalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CriticalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CriticalService",
	HandlerType: (*CriticalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestCritical",
			Handler:    _CriticalService_RequestCritical_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/template.proto",
}
